#!/usr/bin/env bash

me=${BASH_SOURCE[0]}
myname=$(basename "${me%-*}")
[ -L "$me" ] && me=$(readlink -f "$me")
here=$(cd "$(dirname "$me")" && pwd)
usage() { # {{{
    cat <<-EOT
    Usage: $0 <options> [ARGS]
        Options:
          -n NAME - The name of the container to start
          -h      - Show usage

          ARGS are passed to docker / podman as arguments
EOT
} # }}}

die() { # {{{
    local -i code
    code=$1
    shift
    echo "Error! => $*" >&2
    echo >&2
    usage >&2
    # shellcheck disable=SC2086
    exit $code
} # }}}

while getopts :hn:d: opt # {{{
do 
    case $opt in
        n)
            name=$OPTARG
            ;;
        d)
            db=$OPTARG
            ;;
        h) 
            usage
            exit
            ;;
        \?) 
            die 10 "Invalid option '${OPTARG}'"
            ;;
        :) 
            die 27 "Option ${OPTARG} requires an argument"
            ;;
    esac
done # }}}
shift $((OPTIND-1))

: "${name:=slamd}"

muxdir=/tmp/slamd-mux.$$
[ -d "$muxdir" ] || mkdir -vp "$muxdir"

: "${db:=empty}"
dbdir="$here/db/$db"
[ -d "${dbdir}" ] || mkdir -vp "${dbdir}"

: "${SLAMD_ADDRESS:=127.0.0.1}"
echo "SLAMD_ADDRESS is $SLAMD_ADDRESS" >&2
echo "Starting SLAMD" >&2

: "${NO_SLAMD_SERVER:=}"

if [ -z "$NO_SLAMD_SERVER" ]
then
	echo "Starting SLAMD server with one client locally" >&2
	$myname run -it --rm \
		    -e SLAMD_NO_SERVER="$NO_SLAMD_SERVER" \
		    -e SLAMD_ADDRESS="$SLAMD_ADDRESS" \
		    -v "${dbdir}":/usr/local/slamd/webapps/slamd/WEB-INF/db \
		    -v "$muxdir":/tmp/mux -p 2020:8080 \
		    -p 3000:3000 \
		    -p 3001:3001 \
		    -p 3002:3002 \
		    -p 3003:3003 \
		    "$name" "$@"
else
	echo "Starting SLAMD client only" >&2
	$myname run -it --rm \
		    -e SLAMD_NO_SERVER="$NO_SLAMD_SERVER" \
		    -e SLAMD_ADDRESS="$SLAMD_ADDRESS" \
		    -v "${dbdir}":/usr/local/slamd/webapps/slamd/WEB-INF/db \
		    -v "$muxdir":/tmp/mux \
		    "$name" "$@"
fi
# vim: set foldmethod=marker et ts=4 sts=4 sw=4 :
