#!/usr/bin/env bash
# Set $here to the full path to this script
me=${BASH_SOURCE[0]}
myname=$(basename "${me%-*}")
usage() { # {{{
    cat <<-EOT
    Usage: $0 <options> [ARGS]
        Options:
          -n NAME - The name of the container to start
          -h      - Show usage

          ARGS are passed to docker / podman as arguments
EOT
} # }}}

die() { # {{{
    local -i code
    code=$1
    shift
    echo "Error! => $*" >&2
    echo >&2
    usage >&2
    # shellcheck disable=SC2086
    exit $code
} # }}}

while getopts :hn: opt # {{{
do 
    case $opt in
        n)
            name=$OPTARG
            ;;
        h) 
            usage
            exit
            ;;
        ?) 
            die 10 "Invalid option '${OPTARG}'"
            ;;
        :) 
            die 27 "Option ${OPTARG} requires an argument"
            ;;
    esac
done # }}}
shift $((OPTIND-1))

: "${name:=slamd}"

[ -d /tmp/slamd-mux ] || mkdir -p /tmp/slamd-mux
$myname run -it --rm -v /tmp/slamd-mux:/tmp/mux -p 2020:8080 -p 3000:3000 -p 3001:3001 -p 3002:3002 -p 3003:3003 "$name" "$@"
# vim: set foldmethod=marker et ts=4 sts=4 sw=4 :
