#!/bin/sh
exec 2>&1
JRE_HOME=/usr/lib/jvm/java-1.8-openjdk/jre
export JRE_HOME
if [ -z "$SLAMD_NO_SERVER" ]
then
    exec /usr/local/slamd/start-slamd-server.sh 2>&1
else
    echo "SLAMD_NO_SERVER is set, not starting server" >&2
    exec pause
fi
